version: '3'

networks:
  laravel:
    driver: bridge

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: portfolio_nginx
    ports:
      - "127.0.0.1:8026:80"
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - db
    networks:
      - laravel

  db:
    image: postgres:13
    container_name: portfolio_db
    ports:
      - "127.0.0.1:3026:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
      SERVICE_TAGS: dev
      SERVICE_NAME: db
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    container_name: portfolio_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    ports:
      - "127.0.0.1:${PGADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: portfolio_php
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "127.0.0.1:9025:9000"
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: portfolio_artisan
    volumes:
      - ./src:/var/www/html:delegated
    working_dir: /var/www/html
    depends_on:
      - db
    user: laravel
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel